apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: todoapp-daemon
  namespace: mateapp
  labels: 
    app: mate-server
spec: 
  selector:
    matchLabels:
      app: mate-server
  template:
    metadata: 
      labels:
        app: mate-server
    spec:
      containers: 
      - name: mate-server
        image: busyboxplus:curl
        resources:
          requests: 
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        ports:
        - containerPort: 80
          hostPort: 30080
        command: ["sh", "-c", "while true; do curl http://todoapp-service.mateapp.svc:8080; sleep 5; done"]
